#include <malloc.h>
#include <stddef.h>
#include <stdint.h>

#include "buzhash.h"
#include "ringbuf.h"

// This value or its rotated variants will not match any “all ones” or “all
// zeros” mask with a length of 2 bits or more.
#define INITIAL_HASH 0x55555555

static inline uint32_t rotl (uint32_t val, int bits) {
  return (val << bits) | (val >> (32 - bits));
}

static inline uint32_t rotr (uint32_t val, int bits) {
  return (val >> bits) | (val << (32 - bits));
}

static inline buzhash_t *
buzhash_alloc (const unsigned int window_size)
{
  if (window_size < 1 || (window_size % 32) != 0) {
    errno = EINVAL;
    return NULL;
  }

  buzhash_t *restrict bh = calloc (1, sizeof (buzhash_t));
  if (! bh)
    return NULL;

  bh->ringbuf = ringbuf_new (window_size);
  if (! bh->ringbuf) {
    const int errsv = errno;
    free (bh);
    errno = errsv;
    return NULL;
  }

  return bh;
}

buzhash_t *
buzhash_new (const unsigned int window_size_div_32,
             const unsigned int chunk_min_size,
             const unsigned int chunk_max_size,
             const unsigned int mask_bits)
{
  unsigned int window_size = window_size_div_32 * 32;

  buzhash_t *restrict bh = buzhash_alloc (window_size);
  if (! bh)
    return NULL;

  buzhash_t bh_init = { .window_size      = window_size,
                        .chunk_min_size   = chunk_min_size,
                        .chunk_max_size   = chunk_max_size,
                        .mask_bits        = mask_bits,
                        .mask             = (1 << mask_bits) - 1,
                        .ringbuf          = bh->ringbuf,
                        .hash             = INITIAL_HASH,
                        .chunk_total_size = 0 };

  return memcpy (bh, &bh_init, sizeof (buzhash_t));
}

buzhash_t *
buzhash_clone (const buzhash_t *restrict bh_orig)
{
  buzhash_t *restrict bh = buzhash_alloc (bh_orig->window_size);
  if (! bh)
    return NULL;

  ringbuf_copy (bh->ringbuf, bh_orig->ringbuf);

  buzhash_t bh_init = { .window_size      = bh_orig->window_size,
                        .chunk_min_size   = bh_orig->chunk_min_size,
                        .chunk_max_size   = bh_orig->chunk_max_size,
                        .mask_bits        = bh_orig->mask_bits,
                        .mask             = bh_orig->mask,
                        .ringbuf          = bh->ringbuf /* not a typo */,
                        .hash             = bh_orig->hash,
                        .chunk_total_size = bh_orig->chunk_total_size };

  return memcpy (bh, &bh_init, sizeof (buzhash_t));
}

void
buzhash_free (buzhash_t *restrict bh)
{
  ringbuf_free (bh->ringbuf);
  free (bh);
}

void
buzhash_process (buzhash_t *restrict bh,
                 const uint8_t *restrict buf,
                 const unsigned int buf_size,
                 split_ptr split)
{
  unsigned int chunk_local_size = 0;

  for (unsigned int i = 0; i < buf_size; ++i) {
    ++bh->chunk_total_size;
    ++chunk_local_size;

    const uint8_t old_val = ringbuf_put (bh->ringbuf, buf[i]);

    bh->hash = rotl (bh->hash, 1) ^ buztable[old_val] ^ buztable[buf[i]];

    if (((bh->hash & bh->mask) == bh->mask
          && bh->chunk_total_size >= bh->chunk_min_size)
        || bh->chunk_total_size >= bh->chunk_max_size) {
      split (chunk_local_size);

      bh->chunk_total_size = 0;
      chunk_local_size = 0;
    }
  }
}

// See tests/Table.hs for a program that generates this table. It is the
// sequence of 256 big-endian 32-bit words generated by the NIST SP 800-90A
// Hash_DRBG with SHA-512, seeded with all zeros.
const uint32_t buztable[256] =
  { 0xe94edab9, 0x9179f840, 0xeebc76b0, 0x54e83dca, 0xa2db6a7d, 0x5afbe75b,
    0xcfb20209, 0x2f334b39, 0x652e9ebe, 0xdeed6f14, 0xfeff7703, 0x04cb281f,
    0x49fec4b0, 0x5893b190, 0x1c595c7b, 0x25e31af1, 0x044017c8, 0x3daecb45,
    0xd9503f46, 0x5e7aee75, 0x9ed63b9c, 0x427c505a, 0xbf8ce015, 0x249d58d3,
    0xfbbfd0cf, 0x1751dd5d, 0x10d7a4a7, 0xcc2b8265, 0xd4bf4756, 0xa55a3c41,
    0x276a4f2b, 0x310be2e7, 0x9478b0dc, 0xf48f4b6b, 0x5425c035, 0x646e81ee,
    0x9b8522d8, 0xd88fc114, 0x15fdf784, 0x7e91f283, 0xbc54ea00, 0xbdbd0bb3,
    0xbadbfcd0, 0xe520fd65, 0xaa7dae3a, 0x897d3a3b, 0x9904d159, 0xcc9d9371,
    0x24785180, 0xffff22bb, 0xf26f4639, 0xd48616ba, 0xcf45a5f8, 0x82cde4f2,
    0x4a40cc94, 0xa0a2db8c, 0x3717c7cd, 0xc6ebf222, 0x92cfa310, 0x9bf70878,
    0x8c1a2787, 0xbcb1cfed, 0x8f677da1, 0x20ceacd8, 0x3f324759, 0x3659310e,
    0x0e332c11, 0x36176005, 0xdbfbeec0, 0x695504d3, 0xfe1fb6d2, 0x81abe850,
    0x0a6f36df, 0x642690c8, 0x37e241f1, 0xbf0ba1d1, 0x9490e15c, 0x9ba32602,
    0xb555aa75, 0x03ad6b61, 0x501126a8, 0x357d6a10, 0x3c22f73e, 0x5dc380ae,
    0xd81bce47, 0x4bd566d2, 0x97e98ad0, 0x621d0709, 0x9f947397, 0xc24051f5,
    0x8c369bae, 0xb84b3739, 0x82b7369d, 0xd7f5eb36, 0x84e0b030, 0xe9c15d28,
    0xb3f5321a, 0xafc1445f, 0x6da89745, 0xd719e3ee, 0x266a3ad6, 0xacfb8575,
    0xb798ced9, 0xf8aa1e6d, 0xa5806f1c, 0x69931465, 0x1b1d4da4, 0x7fbc76c9,
    0x37f76e5e, 0x3319c349, 0xa9790cc4, 0x1d7d0ff8, 0xe3f965f3, 0x9e33c234,
    0x189870af, 0xa3318776, 0xd56309b6, 0x42fd161e, 0x4caf4d3f, 0x4a6400cd,
    0xd87f7fb3, 0xcce4ab35, 0xce2d4963, 0x8b3bd9d7, 0xff046bd8, 0xa7df7cd0,
    0x2dbc8dce, 0xa20a0a42, 0x12ea4f35, 0x8735c414, 0x1f2820ab, 0xd96f6879,
    0x91a3b0f9, 0xd102748f, 0xea1072f6, 0x9ec778e4, 0x88ce80b0, 0xb37aabc5,
    0xe75bbc4c, 0x1cf5b4f2, 0x5a21c284, 0x6a38d4f7, 0x49746f07, 0x74d225ce,
    0xe4af4927, 0xbc2c2d8a, 0xc3cac4b2, 0xeb7502cd, 0x7b2ad861, 0x2de0f6b4,
    0x894aaa63, 0x0afe43d1, 0xfad42a26, 0xdb352629, 0x40be63a0, 0xe05a2091,
    0xf1859485, 0x528d0a52, 0xc54350aa, 0x1dae8d6f, 0x236872f2, 0x14930e98,
    0x95c61e15, 0xb517b393, 0xa682d66f, 0x5eff4297, 0x1e5005d9, 0xebf81a47,
    0x50b13a89, 0xe4e97ba4, 0x2d909d2c, 0x586f65c9, 0x54169c16, 0x1284b3b1,
    0x3e229ada, 0x7974f355, 0x906214f5, 0x4e6fd675, 0xa557ce29, 0xfea14bff,
    0x4763562c, 0x0804cdf1, 0xc3600edb, 0x81a8c162, 0x317db624, 0xd49e0317,
    0x0daa0379, 0x1bb6ba26, 0x09c80a7d, 0x8410e55f, 0xb40f9d31, 0x22abd234,
    0xe51a5bd7, 0x56ac998f, 0xa834b1bf, 0xf377a14a, 0xe4c804b9, 0xe106b1a2,
    0x9b50c171, 0xdadf642f, 0x055029a2, 0xb028fbd3, 0xed03b12d, 0x5d05815a,
    0xdc34a499, 0x9f8e4031, 0xecefdd48, 0x5d37ec2e, 0xaa1059d6, 0xd5561cd3,
    0x20099ee1, 0x80ed9fd6, 0xbceadbd8, 0xf9ee7e1c, 0xc33d984a, 0x99a96d8a,
    0x7f161024, 0x57d287c3, 0xc5bc853a, 0xfdff9221, 0x680bf3e2, 0x99cd5484,
    0x3de0e5fb, 0x34548af0, 0x7d4c1861, 0xdbf9b617, 0xf1eb6f1a, 0xb9464200,
    0x2d6fd8f3, 0x9e8835f6, 0x1180d7b2, 0xd85f8f66, 0x82b300ca, 0x7d4ec552,
    0x83b99b0b, 0xb72ef88b, 0x687e256c, 0xf74ea72b, 0x349848f0, 0x51cff354,
    0xc124511a, 0xa94e21dd, 0xe487c917, 0xfbe05c92, 0xbe6670b8, 0x6fa5bb06,
    0xe29d8faf, 0x4b9fee88, 0x4af559ab, 0xf46ef559, 0x436cfa2a, 0xe47e23a3,
    0xa10c450f, 0x888f4502, 0xa03d69eb, 0xb582f103 };
